/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p1_diegomaradiaga;

import java.util.ArrayList;

/**
 *
 * @author df346
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ArrayList <String> estados = new ArrayList ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneldeCreacion = new javax.swing.JFrame();
        PanelMenu1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Estados = new javax.swing.JTextField();
        jTextField_Transiciones = new javax.swing.JTextField();
        Crear = new javax.swing.JButton();
        PaneldeComputacion = new javax.swing.JFrame();
        PanelMenu2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Cadena = new javax.swing.JLabel();
        CadenaaComputar = new javax.swing.JTextField();
        BotonComputar = new javax.swing.JButton();
        BotonComputar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textie = new javax.swing.JTextArea();
        PanelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CrearMaquina = new javax.swing.JButton();
        EvaluarCadena = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        PanelMenu1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("   Crear Máquina");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Estados");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Transiciones");

        jTextField_Estados.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Estados.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EstadosActionPerformed(evt);
            }
        });

        jTextField_Transiciones.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Transiciones.setForeground(new java.awt.Color(0, 0, 0));

        Crear.setForeground(new java.awt.Color(0, 0, 0));
        Crear.setText("Crear");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenu1Layout = new javax.swing.GroupLayout(PanelMenu1);
        PanelMenu1.setLayout(PanelMenu1Layout);
        PanelMenu1Layout.setHorizontalGroup(
            PanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenu1Layout.createSequentialGroup()
                .addGroup(PanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenu1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMenu1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Crear))
                    .addGroup(PanelMenu1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Estados, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Transiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        PanelMenu1Layout.setVerticalGroup(
            PanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenu1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Transiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Crear)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout PaneldeCreacionLayout = new javax.swing.GroupLayout(PaneldeCreacion.getContentPane());
        PaneldeCreacion.getContentPane().setLayout(PaneldeCreacionLayout);
        PaneldeCreacionLayout.setHorizontalGroup(
            PaneldeCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PaneldeCreacionLayout.setVerticalGroup(
            PaneldeCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelMenu2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Computar Cadenas");

        Cadena.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Cadena.setForeground(new java.awt.Color(0, 0, 0));
        Cadena.setText("Cadena a computar");

        CadenaaComputar.setBackground(new java.awt.Color(255, 255, 255));
        CadenaaComputar.setForeground(new java.awt.Color(0, 0, 0));

        BotonComputar.setForeground(new java.awt.Color(0, 0, 0));
        BotonComputar.setText("Computar");
        BotonComputar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonComputarMouseClicked(evt);
            }
        });
        BotonComputar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComputarActionPerformed(evt);
            }
        });

        BotonComputar1.setForeground(new java.awt.Color(0, 0, 0));
        BotonComputar1.setText("Menu");
        BotonComputar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComputar1ActionPerformed(evt);
            }
        });

        textie.setColumns(20);
        textie.setRows(5);
        jScrollPane1.setViewportView(textie);

        javax.swing.GroupLayout PanelMenu2Layout = new javax.swing.GroupLayout(PanelMenu2);
        PanelMenu2.setLayout(PanelMenu2Layout);
        PanelMenu2Layout.setHorizontalGroup(
            PanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenu2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(PanelMenu2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(Cadena)
                    .addGroup(PanelMenu2Layout.createSequentialGroup()
                        .addComponent(BotonComputar)
                        .addGap(72, 72, 72)
                        .addComponent(BotonComputar1))
                    .addComponent(CadenaaComputar))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PanelMenu2Layout.setVerticalGroup(
            PanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenu2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(Cadena)
                .addGap(18, 18, 18)
                .addComponent(CadenaaComputar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(PanelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonComputar)
                    .addComponent(BotonComputar1))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout PaneldeComputacionLayout = new javax.swing.GroupLayout(PaneldeComputacion.getContentPane());
        PaneldeComputacion.getContentPane().setLayout(PaneldeComputacionLayout);
        PaneldeComputacionLayout.setHorizontalGroup(
            PaneldeComputacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PaneldeComputacionLayout.setVerticalGroup(
            PaneldeComputacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMenu.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lab P1 - Examen II");

        CrearMaquina.setForeground(new java.awt.Color(0, 0, 0));
        CrearMaquina.setText("Crear Máquina");
        CrearMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearMaquinaActionPerformed(evt);
            }
        });

        EvaluarCadena.setForeground(new java.awt.Color(0, 0, 0));
        EvaluarCadena.setText("Evaluar Cadena");
        EvaluarCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluarCadenaActionPerformed(evt);
            }
        });

        Salir.setForeground(new java.awt.Color(0, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrearMaquina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EvaluarCadena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(CrearMaquina)
                .addGap(40, 40, 40)
                .addComponent(EvaluarCadena)
                .addGap(40, 40, 40)
                .addComponent(Salir)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearMaquinaActionPerformed
        PaneldeCreacion.setVisible(true);
        PaneldeCreacion.setSize(300, 300);
        PaneldeCreacion.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_CrearMaquinaActionPerformed

    private void EvaluarCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluarCadenaActionPerformed
        PaneldeComputacion.setVisible(true);
        PaneldeComputacion.setSize(303, 394);
        PaneldeComputacion.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_EvaluarCadenaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
    //M.MaquinaEstados();
    String Estados = jTextField_Estados.getText();
    String Transiciones = jTextField_Transiciones.getText();
    M = new MaquinaEstados(Estados,Transiciones);
    PaneldeCreacion.dispose();
    this.setVisible(true);
    }//GEN-LAST:event_CrearActionPerformed
    MaquinaEstados M;
    private void BotonComputar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComputar1ActionPerformed
        PaneldeComputacion.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_BotonComputar1ActionPerformed
         
    private void jTextField_EstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EstadosActionPerformed
        
    }//GEN-LAST:event_jTextField_EstadosActionPerformed

    private void BotonComputarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonComputarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonComputarMouseClicked

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearMouseClicked

    private void BotonComputarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComputarActionPerformed
        String x = CadenaaComputar.getText();
        String retorno = M.Computar(x);
        textie.setText(retorno);
        
    }//GEN-LAST:event_BotonComputarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonComputar;
    private javax.swing.JButton BotonComputar1;
    private javax.swing.JLabel Cadena;
    private javax.swing.JTextField CadenaaComputar;
    private javax.swing.JButton Crear;
    private javax.swing.JButton CrearMaquina;
    private javax.swing.JButton EvaluarCadena;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelMenu1;
    private javax.swing.JPanel PanelMenu2;
    private javax.swing.JFrame PaneldeComputacion;
    private javax.swing.JFrame PaneldeCreacion;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Estados;
    private javax.swing.JTextField jTextField_Transiciones;
    private javax.swing.JTextArea textie;
    // End of variables declaration//GEN-END:variables
}
